name: Clone
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '00 12 */15 * *'

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: tester
          run: |
            wget https://github.com/RogerioLS/Push_Swap-42sp/blob/main/tester_roger-42sp/push_swap_tester.sh
            chmod 777 push_swap_tester.sh
            chmod 777 checker_linux
            chmod 777 push_swap
            mkdir tester_roger-42sp/
            mv push_swap_tester.sh tester_roger-42sp/
            ls -la
            tester_roger-42sp/./push_swap_tester.sh 100 10
