name: Clone
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '00 12 */15 * *'

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: tester
          run: |
            git clone https://github.com/RogerioLS/tester_run_clone.git
            ./tester_run_clone/tester_roger-42sp/./push_swap_tester.sh 5 10
