name: Clone
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '00 12 */15 * *'

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: tester
          run: |
            git clone https://github.com/RogerioLS/tester_run_clone
            chmod 777 tester_run_clone/push_swap_tester.sh
            chmod 777 checker_linux
            chmod 777 push_swap
            ls
            tester_run_clone/./push_swap_tester.sh 100 10
