name: Clone
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '00 12 */15 * *'

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            repository: RogerioLS/tester_run_clone
        - name: tester
          run: |
            ls
            cd tester_roger-42sp/
            ls
        - uses: actions/checkout@v2
        - name: tester-2
          run: |
            ls